GET http://localhost:5501/notify/
Content-Type: application/json
Authorization: Bearer {eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODhkNWQ2ZGI3ZWFlYzM5YWMxZmVlZTUiLCJpYXQiOjE3Njk0OTI5MzcsImV4cCI6MTc2OTU3OTMzN30.GEftoO63Ho8Zpu2uW5Mo3aUXoZNtQ6JoBy015_8zRmg}
